title: Leonardo Endrizzi
description: Personal Website of Leonardo Endrizzi

url: https://leonardendrizzi.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: Blog
      url: /blog
    - title: Research
      url: /research
    - title: Teaching
      url: /teaching
    - title: CV
      url: /cv
    - title: About Me
      url: /about
    - title: Contact
      url: /contact

social:
    github: leonardendrizzi
    #twitter: brianmaierjr
    #facebook: brianmaierjr
    email: leonardo.endrizzi@outlook.it
    linkedin: leonardo-endrizzi-47173621a
    #youtube: RickAstleyYT
    #tumblr: i-am-a-fish

google_analytics: "UA-58263416-1"

disqus:
    shortname: leonardendrizzi
